### ISSUE TITLE
Add haproxy 2.5, 2.6 and 2.7

### ISSUE THREAD

**Issue by ricain59** [DBezemer/rpm-haproxy#57]
Hi,

It's possible you had rpm build for haproxy 2.5, 2.6 and 2.7?

Thank you for your job.

**Comment by thedoc31** [comment]
Because the Makefile is so good and the haproxy project is so consistent, it's not that difficult to tell it what the version you want to compile. Just clone the repository and edit the Makefile. Add a question mark directly after `MAINVERSION`:
example:
`MAINVERSION?=2.4` 

This will allow `MAINVERSION` to be passed as a parameter like `USE_LUA` or `NO_SUDO` and you can just add your desired version via commandline when you run make.
`make MAINVERSION=2.5`
If you don't pass `MAINVERSION`, make will just use whatever the default is for that variable. 

@DBezemer It doesn't seem like the differences between haproxy versions are drastic enough to need a branch for every new minor version of haproxy. With the HAProxy team's accelerated development schedule (2 minor releases per year now), do you think it might make sense to create a `generic` or `dev` branch with this change? I can create a PR for you as soon as there's an appropriate place for it to go. I don't want to PR it into `2.4` since there's already established history there.

**Comment by DBezemer** [comment]
@thedoc31 the main issue is that previously HAProxy hasn't always been forward/backward compatible and the lua version dependency has a tendency to change between releases. Having a dev branch isn't a bad idea tho with having the option to specify the specific version when compiling, so feel free to make a pull request again this branch (I've just created dev).

**Comment by thedoc31** [comment]
@DBezemer Great, just submitted #63 for it. Let me know if you want any other changes.
