### ISSUE TITLE
Support for HAProxy 1.8.1

### ISSUE THREAD

**Issue by pietervogelaar** [DBezemer/rpm-haproxy#7]
Do you have any idea how to support version 1.8.1?

The file haproxy-systemd-wrapper is no longer available in 1.8.1. I removed the install and chmod step in the build for it. With that I was able to build the package. However starting /usr/sbin/haproxy directly doesn't seem to work:

/usr/lib/systemd/system/haproxy.service

```
[Unit]
Description=HAProxy Load Balancer
After=syslog.target network.target

[Service]
ExecStart=/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid
ExecReload=/bin/kill -USR2 $MAINPID
KillMode=mixed

[Install]
WantedBy=multi-user.target
```

**Comment by khdevel** [comment]
@pietervogelaar I also need such RPM, so I have worked on it and here is my PR: https://github.com/DBezemer/rpm-haproxy/pull/8

Please checkout if it works for you. My build is for Centos7 and it seems to work fine.
I did not check it with special configuration because I have to migrate from 1.5, so it needs a time and tests. But the main process with default configuration works good.

*Remark:*
When I set an option *-W* or put *master-worker* in configuration haproxy.service was in **failed** state after the *systemctl stop haproxy.service* was performed. So, it needs to be checked what is the reason of that and fix it.

**Comment by DBezemer** [comment]
Finalized in 660295962ab79d5062dd97cc5f6952553776a0f6

**Comment by khdevel** [comment]
Thank you!

**Comment by next-carlosleon** [comment]
> Remark:
When I set an option -W or put master-worker in configuration haproxy.service was in failed state after the systemctl stop haproxy.service was performed. So, it needs to be checked what is the reason of that and fix it.

I am having the same issue. Do you know what is going on?

Thanks

**Comment by DBezemer** [comment]
@beeva-carlosleon master-worker probably requires to run haproxy without a pid file, I'll do some testing and if this is the case will release an updated service file together with the 1.8.5 release

**Comment by next-carlosleon** [comment]
Thanks @DBezemer and great work! :)
